---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-notthedroid-com
  namespace: default
spec:
  secretName: local-notthedroid-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.notthedroid.com"
  dnsNames:
  - "local.notthedroid.com"
  - "*.local.notthedroid.com"