installCRDs: false
replicaCount: 3 # change to number of masternodes
extraArgs: # required for querying for certificate
  - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
  - --dns01-recursive-nameservers-only
podDnsPolicy: None  # Won't inherit DNS from host machine
podDnsConfig:
  nameservers:
    - 1.1.1.1
    - 9.9.9.9